[project]
name = "proyecto-pruebas"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "GabrielSerranoUCR", email = "gabriel.serranorojas@ucr.ac.cr" }
]
requires-python = ">=3.13"
dependencies = [
    "scikit-learn>=1.9.0",
    "scipy>=1.18.1",
]

[project.scripts]
proyecto-pruebas = "proyecto_pruebas.main:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pylint>=4.0.8",
    "pytest>=9.1.1",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
